name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: python --version
      - run: cd 1/ && python fizzbuzz.py
      - run: cd 2/ && python balance.py
      - run: cd 3/ && python setup.py test
